language: php
sudo: false

php:
  - "7.1"
  - "7.2"
  - "7.3"

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist --no-interaction

script:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; else vendor/bin/phpunit; fi
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then vendor/bin/php-cs-fixer fix --config=vendor/ixocreate/coding-standard/.php_cs -v --dry-run --using-cache=no --path-mode=intersection `git diff --name-only --diff-filter=ACMRTUXB $TRAVIS_COMMIT_RANGE`; fi

after_success:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then php vendor/bin/php-coveralls -v; fi

notifications:
  email: false
  slack:
    secure: "X0A074s9toJgoxez7uO3eHuX3NOr2j2xOtEBJfQmXDWjMgREuS98gzGZaY4a/t17wm1TbpFIsnqJEUlZzj8ZU5MdxXKMs81ndCxb6VQ4CmxwJM6Pt5NYizLDVtJAlSLgacuQX+Ln9HsANrEqXD+zy/bomM3NCE1mIB2djkbEupVQ9roZPLKJZ2tMCJiMjF7p4WxU27hEL432f5uOQ2cfYRagnJJYuoQQlF4/y5sULMQFO5TNACBAkQu4YdrMCz/g8pdIvAXSHzZdZztijLSf0XJvz3JLGsBoydRFIbNKIWbEoLmc5df78htyCeV1nmteAOCBDjiesjkfBaCG7Av+86dF4JU9szaT+uuvRUGLxTu1DK3YpF0sAuIJM07GT1tqUHRNU2yB6XxOpDrJkdgymFudfqjIwO538L0yf1Px0cbGp+Ck13UlfpMnrkBt9vi7E/GDx7E2WB87UekORgEV8aXhl3eUlXIWHDjureoYa+BnaR+JcU+jhE3dd895m6zhQk2/pkcQJRvypBhga35rt1FbyVRAjPzVjGhplCjabxtrZB1C6gu8LQycrFMAxkVrG1tr8ICkuAfKbIeMuO+H8qroosO3/kNnBFep0ZkhuP9WY9h/uiDO33i7BEDRusvpdqxIDh7iNBf2TSh1R9Oy5/mOpreGPJg/iY+2g00o6j0="
    on_success: change # default: always
    on_failure: change # default: always
